IF OBJECT_ID ('dbo.TB_ENTRADA') IS NOT NULL
	DROP TABLE dbo.TB_ENTRADA
GO

CREATE TABLE dbo.TB_ENTRADA
	(
	PROD_ID        INT NOT NULL,
	LOJA_ID        INT NOT NULL,
	FORNEC_ID      INT NOT NULL,
	QUANTIDADE     NUMERIC (18) NOT NULL,
	MARCA          VARCHAR (20) NOT NULL,
	VALOR          NUMERIC (18) NOT NULL,
	MODELO         VARCHAR (30) NOT NULL,
	TRANSPORTADORA VARCHAR (40) NULL,
	DATA_ENTREGA   DATE NULL,
	LOTE           INT NOT NULL,
	VALIDADE       DATE NULL,
	NF             INT NOT NULL,
	CONSTRAINT FK_LOJAS FOREIGN KEY (LOJA_ID) REFERENCES dbo.TB_LOJAS (ID_LOJA),
	CONSTRAINT FK_FORNEC FOREIGN KEY (FORNEC_ID) REFERENCES dbo.TB_FORNECEDORES (ID_FORNEC)
	)
GO

IF OBJECT_ID ('dbo.TB_FORNECEDORES') IS NOT NULL
	DROP TABLE dbo.TB_FORNECEDORES
GO

CREATE TABLE dbo.TB_FORNECEDORES
	(
	ID_FORNEC   INT IDENTITY NOT NULL,
	CNPJ        VARCHAR (10) NULL,
	IE          VARCHAR (10) NULL,
	NOME        VARCHAR (50) NOT NULL,
	RAZAO       VARCHAR (50) NULL,
	FANTASIA    VARCHAR (40) NULL,
	TIPO        CHAR (1) NOT NULL,
	CEP         VARCHAR (10) NOT NULL,
	PAIS        VARCHAR (40) NOT NULL,
	UF          CHAR (2) NOT NULL,
	CIDADE      VARCHAR (40) NOT NULL,
	BAIRRO      VARCHAR (40) NOT NULL,
	RUA         VARCHAR (50) NOT NULL,
	NUMERO      VARCHAR (10) NOT NULL,
	COMPLEMENTO VARCHAR (40) NULL,
	DATA        DATE NULL,
	EMAIL       VARCHAR (40) NULL,
	TELEFONE    VARCHAR (10) NULL,
	AREA        VARCHAR (20) NULL,
	PRIMARY KEY (ID_FORNEC)
	)
GO

IF OBJECT_ID ('dbo.TB_LOJAS') IS NOT NULL
	DROP TABLE dbo.TB_LOJAS
GO

CREATE TABLE dbo.TB_LOJAS
	(
	ID_LOJA  INT IDENTITY NOT NULL,
	CNPJ     VARCHAR (10) NOT NULL,
	IE       VARCHAR (10) NULL,
	NOME     VARCHAR (50) NOT NULL,
	RAZAO    VARCHAR (50) NULL,
	FANTASIA VARCHAR (50) NULL,
	TIPO     CHAR (1) NOT NULL,
	CEP      VARCHAR (10) NOT NULL,
	PAIS     VARCHAR (40) NOT NULL,
	UF       CHAR (2) NOT NULL,
	CIDADE   VARCHAR (40) NOT NULL,
	BAIRRO   VARCHAR (40) NOT NULL,
	RUA      VARCHAR (50) NOT NULL,
	NUMERO   VARCHAR (10) NOT NULL,
	TELEFONE VARCHAR (10) NULL,
	EMAIL    VARCHAR (30) NULL,
	DATA_CAD DATE NULL,
	PRIMARY KEY (ID_LOJA)
	)
GO           IF OBJECT_ID ('dbo.TB_PRODUTOS') IS NOT NULL
	DROP TABLE dbo.TB_PRODUTOS
GO

CREATE TABLE dbo.TB_PRODUTOS
	(
	ID_PRODUTO INT IDENTITY NOT NULL,
	DESCRICAO  VARCHAR (40) NULL,
	VALOR      INT NULL,
	IMAGEM     VARBINARY (1) NULL,
	PRIMARY KEY (ID_PRODUTO)
	)
GO

IF OBJECT_ID ('dbo.TB_USUARIOS') IS NOT NULL
	DROP TABLE dbo.TB_USUARIOS
GO

CREATE TABLE dbo.TB_USUARIOS
	(
	ID_USUARIO  INT IDENTITY NOT NULL,
	NOME        VARCHAR (100) NOT NULL,
	MATRICULA   VARCHAR (4) NOT NULL,
	CPF         VARCHAR (14) NOT NULL,
	GRUPO       VARCHAR (20) NOT NULL,
	CARGO       VARCHAR (30) NOT NULL,
	CEP         VARCHAR (8) NOT NULL,
	PAIS        VARCHAR (40) NOT NULL,
	UF          CHAR (2) NOT NULL,
	CIDADE      VARCHAR (50) NOT NULL,
	BAIRRO      VARCHAR (50) NOT NULL,
	RUA         VARCHAR (50) NOT NULL,
	NUMERO      VARCHAR (10) NOT NULL,
	COMPLEMENTO VARCHAR (60) NOT NULL,
	TELEFONE    VARCHAR (15) NULL,
	DATA_NASC   DATE NOT NULL,
	SEXO        CHAR (1) NOT NULL,
	EMAIL       VARCHAR (100) NULL,
	SENHA       VARCHAR (255) NOT NULL,
	UNIQUE (MATRICULA)
	)
GO



